stages:
  train_cnn:
    cmd: python src/train.py
    deps:
      - src/train.py
      - src/model.py
      - data/Butterfly/train
      - data/Butterfly/valid
    params:
      - train.epochs
      - train.lr
      - train.batch_size
      - train.train_dir
      - train.val_dir
    outs:
      - model/model.pt
    metrics:
      - metrics.json

  evaluate_cnn:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - src/model.py
      - model/model.pt
      - data/Butterfly/test
    params:
      - evaluate.test_dir
    metrics:
      - test_metrics.json

