stages:
  train_cnn:
    cmd: python src/train.py
    deps:
    - data/train
    - data/val
    - src/model.py
    - src/train.py
    params:
    - train.batch_size
    - train.epochs
    - train.lr
    outs:
    - model/model.pt
    metrics:
    - metrics.json:
        cache: false
